# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Build
      run: dotnet build --no-restore  
    
    - name: Publish
      run: dotnet publish --no-restore --no-build --output ./publish
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ./publish
        
  deploy:
    needs: build
    environment: desenvolvimento
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./publish
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'webappnttdata'
          package: ./publish